image: Visual Studio 2022
build_script:
  - cmd: dotnet restore
  - cmd: dotnet pack SDL2-CS.csproj -c:Release --include-symbols /p:Version=%APPVEYOR_BUILD_VERSION%
test: off
version: 1.0.{build}-alpha
artifacts:
  - path: 'bin\Release\*.nupkg'
